version: 2

seeds:
  - name: health_eligibility_span
    config:
      column_types:
        eligibility_span_id: varchar
        member_id: varchar
        benefit_plan_id: varchar
        start_date: date
        end_date: date
        span_reason: varchar
